#!/usr/bin/env ts-node

/**
 * Excel to Database Sync Script
 * 
 * This script synchronizes book data from Excel files generated by the Python ebook system
 * to the LINE Bot's MySQL database.
 * 
 * Usage:
 *   npm run sync:excel -- --file path/to/excel/file.xlsx
 *   npm run sync:excel -- --directory path/to/excel/directory
 *   npm run sync:excel -- --monitor path/to/excel/directory
 */

import { program } from 'commander';
import { join, resolve } from 'path';
import { BookSyncService } from '../src/services/BookSyncService';
import { databaseService } from '../src/services/DatabaseService';

// 設定命令行參數
program
  .name('sync-excel-to-db')
  .description('Synchronize Excel book data to database')
  .version('1.0.0');

program
  .command('file')
  .description('Sync a single Excel file to database')
  .argument('<filepath>', 'Path to Excel file')
  .option('-v, --verbose', 'Enable verbose logging')
  .action(async (filepath: string, options) => {
    await syncSingleFile(filepath, options.verbose);
  });

program
  .command('directory')
  .description('Sync all Excel files in a directory to database')
  .argument('<dirpath>', 'Path to directory containing Excel files')
  .option('-p, --pattern <pattern>', 'File name pattern (regex)')
  .option('-v, --verbose', 'Enable verbose logging')
  .action(async (dirpath: string, options) => {
    await syncDirectory(dirpath, options.pattern, options.verbose);
  });

program
  .command('monitor')
  .description('Monitor directory for new Excel files and auto-sync')
  .argument('<dirpath>', 'Path to directory to monitor')
  .option('-i, --interval <ms>', 'Check interval in milliseconds', '60000')
  .option('-p, --pattern <pattern>', 'File name pattern (regex)')
  .option('-v, --verbose', 'Enable verbose logging')
  .action(async (dirpath: string, options) => {
    await monitorDirectory(dirpath, parseInt(options.interval), options.pattern, options.verbose);
  });

program
  .command('stats')
  .description('Show sync statistics')
  .action(async () => {
    await showStats();
  });

/**
 * 同步單個檔案
 */
async function syncSingleFile(filepath: string, verbose: boolean = false): Promise<void> {
  const syncService = new BookSyncService();
  
  try {
    console.log(`🚀 Starting sync for file: ${filepath}`);
    
    const absolutePath = resolve(filepath);
    const result = await syncService.syncExcelFileToDatabase(absolutePath);
    
    if (result.success) {
      console.log(`✅ ${result.message}`);
      console.log(`📊 Statistics:`);
      console.log(`   - Total books: ${result.totalBooks}`);
      console.log(`   - Successful syncs: ${result.successfulSyncs}`);
      console.log(`   - Failed syncs: ${result.failedSyncs}`);
      console.log(`   - Duration: ${result.duration}ms`);
      
      if (verbose && result.errors.length > 0) {
        console.log(`⚠️  Errors/Warnings:`);
        result.errors.forEach(error => console.log(`   - ${error}`));
      }
    } else {
      console.error(`❌ ${result.message}`);
      if (result.errors.length > 0) {
        console.error(`Errors:`);
        result.errors.forEach(error => console.error(`   - ${error}`));
      }
      process.exit(1);
    }
    
  } catch (error) {
    console.error(`❌ Sync failed:`, error);
    process.exit(1);
  }
}

/**
 * 同步目錄下所有檔案
 */
async function syncDirectory(dirpath: string, pattern?: string, verbose: boolean = false): Promise<void> {
  const syncService = new BookSyncService();
  
  try {
    console.log(`🚀 Starting batch sync for directory: ${dirpath}`);
    
    const absolutePath = resolve(dirpath);
    const filePattern = pattern ? new RegExp(pattern) : undefined;
    
    if (filePattern) {
      console.log(`📋 Using file pattern: ${pattern}`);
    }
    
    const result = await syncService.syncDirectoryToDatabase(absolutePath, filePattern);
    
    if (result.success) {
      console.log(`✅ ${result.message}`);
      console.log(`📊 Batch Statistics:`);
      console.log(`   - Total files: ${result.totalFiles}`);
      console.log(`   - Processed files: ${result.processedFiles}`);
      console.log(`   - Total books: ${result.totalBooks}`);
      console.log(`   - Successful syncs: ${result.successfulSyncs}`);
      console.log(`   - Failed syncs: ${result.failedSyncs}`);
      console.log(`   - Duration: ${result.duration}ms`);
      
      if (verbose && result.fileResults.length > 0) {
        console.log(`📄 File Results:`);
        result.fileResults.forEach(fileResult => {
          const status = fileResult.success ? '✅' : '❌';
          console.log(`   ${status} ${fileResult.filePath}: ${fileResult.successfulSyncs}/${fileResult.totalBooks} books`);
          
          if (fileResult.errors.length > 0) {
            fileResult.errors.forEach(error => console.log(`      ⚠️  ${error}`));
          }
        });
      }
    } else {
      console.error(`❌ ${result.message}`);
      process.exit(1);
    }
    
  } catch (error) {
    console.error(`❌ Batch sync failed:`, error);
    process.exit(1);
  }
}

/**
 * 監控目錄
 */
async function monitorDirectory(
  dirpath: string, 
  interval: number, 
  pattern?: string, 
  verbose: boolean = false
): Promise<void> {
  const syncService = new BookSyncService();
  
  try {
    console.log(`👀 Starting directory monitoring: ${dirpath}`);
    console.log(`⏱️  Check interval: ${interval}ms`);
    
    const absolutePath = resolve(dirpath);
    const filePattern = pattern ? new RegExp(pattern) : undefined;
    
    if (filePattern) {
      console.log(`📋 Using file pattern: ${pattern}`);
    }
    
    // 設定優雅關閉
    process.on('SIGINT', () => {
      console.log('\n🛑 Stopping directory monitoring...');
      process.exit(0);
    });
    
    process.on('SIGTERM', () => {
      console.log('\n🛑 Stopping directory monitoring...');
      process.exit(0);
    });
    
    await syncService.startDirectoryMonitoring(absolutePath, interval, filePattern);
    
    console.log(`✅ Directory monitoring started successfully`);
    console.log(`Press Ctrl+C to stop monitoring`);
    
    // 保持程序運行
    await new Promise(() => {}); // 永遠等待
    
  } catch (error) {
    console.error(`❌ Directory monitoring failed:`, error);
    process.exit(1);
  }
}

/**
 * 顯示統計資料
 */
async function showStats(): Promise<void> {
  const syncService = new BookSyncService();
  
  try {
    console.log(`📊 Fetching sync statistics...`);
    
    const stats = await syncService.getSyncStats();
    
    console.log(`📈 Sync Statistics:`);
    console.log(`   - Total books in database: ${stats.totalBooksInDatabase}`);
    console.log(`   - Notified books: ${stats.notifiedBooks}`);
    console.log(`   - Unnotified books: ${stats.unnotifiedBooks}`);
    console.log(`   - Recent books (7 days): ${stats.recentBooks}`);
    console.log(`   - Last sync time: ${stats.lastSyncTime.toLocaleString()}`);
    
  } catch (error) {
    console.error(`❌ Failed to get statistics:`, error);
    process.exit(1);
  }
}

/**
 * 主程序入口
 */
async function main(): Promise<void> {
  try {
    // 測試資料庫連線
    const isConnected = await databaseService.testConnection();
    if (!isConnected) {
      console.error('❌ Database connection failed. Please check your database configuration.');
      process.exit(1);
    }
    
    // 執行遷移
    console.log('🔄 Running database migrations...');
    await databaseService.runMigrations();
    console.log('✅ Database migrations completed');
    
    // 解析命令行參數
    await program.parseAsync();
    
  } catch (error) {
    console.error('❌ Application error:', error);
    process.exit(1);
  }
}

// 如果直接執行此腳本
if (require.main === module) {
  main().catch(error => {
    console.error('❌ Unhandled error:', error);
    process.exit(1);
  });
}

export { syncSingleFile, syncDirectory, monitorDirectory, showStats };