import * as XLSX from 'xlsx';
import { promises as fs } from 'fs';
import { ExcelBookData } from '../types/NewBook';

/**
 * Service for reading Excel files generated by the Python ebook system
 */
export class ExcelReaderService {
  
  /**
   * 讀取 Excel 檔案並解析新書資料
   * @param filePath Excel 檔案路徑
   * @returns Promise<ExcelBookData[]> 解析後的新書資料陣列
   */
  async readExcelFile(filePath: string): Promise<ExcelBookData[]> {
    try {
      // 檢查檔案是否存在
      await fs.access(filePath);
      
      // 讀取 Excel 檔案
      const workbook = XLSX.readFile(filePath);
      
      // 取得第一個工作表
      const sheetName = workbook.SheetNames[0];
      if (!sheetName) {
        throw new Error('No worksheets found in Excel file');
      }
      
      const worksheet = workbook.Sheets[sheetName];
      if (!worksheet) {
        throw new Error(`Worksheet ${sheetName} not found`);
      }
      
      // 將工作表轉換為 JSON 格式
      const rawData = XLSX.utils.sheet_to_json(worksheet, { header: 1 });
      
      if (!rawData || rawData.length < 2) {
        throw new Error('Excel file is empty or has no data rows');
      }
      
      // 取得標題行
      const headers = rawData[0] as string[];
      
      // 驗證必要的欄位
      this.validateHeaders(headers);
      
      // 解析資料行
      const books: ExcelBookData[] = [];
      
      for (let i = 1; i < rawData.length; i++) {
        const row = rawData[i] as any[];
        
        if (!row || row.length === 0) {
          continue; // 跳過空行
        }
        
        try {
          const bookData = this.parseRowData(headers, row);
          if (bookData && bookData.book_code && bookData.title) {
            books.push(bookData);
          }
        } catch (error) {
          console.warn(`Failed to parse row ${i + 1}:`, error);
          // 繼續處理其他行，不中斷整個解析過程
        }
      }
      
      console.log(`Successfully parsed ${books.length} books from Excel file: ${filePath}`);
      return books;
      
    } catch (error) {
      console.error('Error reading Excel file:', error);
      throw new Error(`Failed to read Excel file: ${error}`);
    }
  }

  /**
   * 驗證 Excel 標題行是否包含必要欄位
   * @private
   */
  private validateHeaders(headers: string[]): void {
    const requiredHeaders = ['書號', '書名'];
    const missingHeaders = requiredHeaders.filter(header => 
      !headers.some(h => h && h.includes(header))
    );
    
    if (missingHeaders.length > 0) {
      throw new Error(`Missing required headers: ${missingHeaders.join(', ')}`);
    }
  }

  /**
   * 解析單行資料
   * @private
   */
  private parseRowData(headers: string[], row: any[]): ExcelBookData | null {
    const bookData: Partial<ExcelBookData> = {};
    
    // 建立標題到索引的映射
    const headerMap = new Map<string, number>();
    headers.forEach((header, index) => {
      if (header) {
        headerMap.set(header.trim(), index);
      }
    });
    
    // 解析各個欄位
    const bookCode = this.getCellValue(row, this.findHeaderIndex(headerMap, ['書號']));
    const title = this.getCellValue(row, this.findHeaderIndex(headerMap, ['書名']));
    
    // 驗證必要欄位
    if (!bookCode || !title) {
      return null;
    }
    
    bookData.book_code = bookCode;
    bookData.title = title;
    
    const author = this.getCellValue(row, this.findHeaderIndex(headerMap, ['作者']));
    if (author) bookData.author = author;
    
    const pdfFilename = this.getCellValue(row, this.findHeaderIndex(headerMap, ['PDF檔名', 'PDF文件名']));
    if (pdfFilename) bookData.pdf_filename = pdfFilename;
    
    // 檔案大小處理
    const fileSizeStr = this.getCellValue(row, this.findHeaderIndex(headerMap, ['檔案大小', '檔案大小(MB)']));
    if (fileSizeStr) {
      const fileSize = parseFloat(fileSizeStr.toString());
      if (!isNaN(fileSize)) {
        bookData.file_size_mb = fileSize;
      }
    }
    
    const processingMethod = this.getCellValue(row, this.findHeaderIndex(headerMap, ['處理方式']));
    if (processingMethod) bookData.processing_method = processingMethod;
    
    const summary = this.getCellValue(row, this.findHeaderIndex(headerMap, ['摘要']));
    if (summary) bookData.summary = summary;
    
    const downloadUrl = this.getCellValue(row, this.findHeaderIndex(headerMap, ['下載連結', '下載網址']));
    if (downloadUrl) bookData.download_url = downloadUrl;
    
    // 處理時間
    const timestampStr = this.getCellValue(row, this.findHeaderIndex(headerMap, ['處理時間']));
    if (timestampStr) {
      bookData.processing_timestamp = timestampStr.toString();
    }
    
    return bookData as ExcelBookData;
  }

  /**
   * 尋找標題索引
   * @private
   */
  private findHeaderIndex(headerMap: Map<string, number>, possibleHeaders: string[]): number {
    for (const header of possibleHeaders) {
      const index = headerMap.get(header);
      if (index !== undefined) {
        return index;
      }
    }
    return -1;
  }

  /**
   * 取得儲存格值
   * @private
   */
  private getCellValue(row: any[], index: number): string | null {
    if (index < 0 || index >= row.length) {
      return null;
    }
    
    const value = row[index];
    if (value === null || value === undefined || value === '') {
      return null;
    }
    
    return value.toString().trim();
  }

  /**
   * 讀取指定目錄下的所有 Excel 檔案
   * @param directoryPath 目錄路徑
   * @param filePattern 檔案名稱模式（可選）
   * @returns Promise<string[]> Excel 檔案路徑陣列
   */
  async findExcelFiles(directoryPath: string, filePattern?: RegExp): Promise<string[]> {
    try {
      const files = await fs.readdir(directoryPath);
      const excelFiles = files.filter(file => {
        const isExcel = file.endsWith('.xlsx') || file.endsWith('.xls');
        if (!isExcel) return false;
        
        if (filePattern) {
          return filePattern.test(file);
        }
        
        return true;
      });
      
      return excelFiles.map(file => `${directoryPath}/${file}`);
    } catch (error) {
      console.error('Error finding Excel files:', error);
      throw new Error(`Failed to find Excel files in directory: ${directoryPath}`);
    }
  }

  /**
   * 批量讀取多個 Excel 檔案
   * @param filePaths Excel 檔案路徑陣列
   * @returns Promise<ExcelBookData[]> 所有檔案的新書資料陣列
   */
  async readMultipleExcelFiles(filePaths: string[]): Promise<ExcelBookData[]> {
    const allBooks: ExcelBookData[] = [];
    
    for (const filePath of filePaths) {
      try {
        const books = await this.readExcelFile(filePath);
        allBooks.push(...books);
        console.log(`Processed ${books.length} books from ${filePath}`);
      } catch (error) {
        console.error(`Failed to process file ${filePath}:`, error);
        // 繼續處理其他檔案
      }
    }
    
    return allBooks;
  }

  /**
   * 驗證 Excel 資料的完整性
   * @param books 新書資料陣列
   * @returns 驗證結果統計
   */
  validateExcelData(books: ExcelBookData[]): {
    total: number;
    valid: number;
    invalid: number;
    duplicates: number;
    issues: string[];
  } {
    const issues: string[] = [];
    const bookCodes = new Set<string>();
    let validCount = 0;
    let duplicateCount = 0;
    
    for (const book of books) {
      // 檢查必要欄位
      if (!book.book_code || !book.title) {
        issues.push(`Missing required fields: book_code=${book.book_code}, title=${book.title}`);
        continue;
      }
      
      // 檢查重複書號
      if (bookCodes.has(book.book_code)) {
        duplicateCount++;
        issues.push(`Duplicate book code: ${book.book_code}`);
        continue;
      }
      
      bookCodes.add(book.book_code);
      validCount++;
    }
    
    return {
      total: books.length,
      valid: validCount,
      invalid: books.length - validCount,
      duplicates: duplicateCount,
      issues
    };
  }

  /**
   * 讀取網站監控 Excel 檔案並解析內容
   * @param filePath Excel 檔案路徑
   * @returns Promise<WebsiteMonitoringData> 解析後的網站監控資料
   */
  async readWebsiteMonitoringExcel(filePath: string): Promise<import('../types/WebsiteMonitoring').WebsiteMonitoringData> {
    try {
      // 檢查檔案是否存在
      await fs.access(filePath);
      
      // 讀取 Excel 檔案
      const workbook = XLSX.readFile(filePath);
      
      const result: import('../types/WebsiteMonitoring').WebsiteMonitoringData = {};
      
      // 處理各個工作表
      for (const sheetName of workbook.SheetNames) {
        const worksheet = workbook.Sheets[sheetName];
        if (!worksheet) continue;
        
        const rawData = XLSX.utils.sheet_to_json(worksheet, { header: 1 }) as any[][];
        
        if (!rawData || rawData.length < 2) {
          continue; // 跳過空的工作表
        }
        
        const headers = rawData[0] as string[];
        
        // 根據工作表名稱判斷內容類型
        if (sheetName.includes('輪播') || sheetName.includes('carousel')) {
          result.carousel = this.parseCarouselData(headers, rawData.slice(1));
        } else if (sheetName.includes('取消') || sheetName.includes('cancellation')) {
          result.cancellation = this.parseCancellationData(headers, rawData.slice(1));
        } else if (sheetName.includes('消息') || sheetName.includes('news')) {
          result.news = this.parseNewsData(headers, rawData.slice(1));
        } else if (sheetName.includes('媒體') || sheetName.includes('media')) {
          result.media = this.parseMediaData(headers, rawData.slice(1));
        }
      }
      
      console.log(`Successfully parsed website monitoring Excel file: ${filePath}`);
      return result;
      
    } catch (error) {
      console.error('Error reading website monitoring Excel file:', error);
      throw new Error(`Failed to read website monitoring Excel file: ${error}`);
    }
  }

  /**
   * 解析輪播內容資料
   * @private
   */
  private parseCarouselData(headers: string[], rows: any[][]): import('../types/WebsiteMonitoring').CarouselContent[] {
    const headerMap = this.createHeaderMap(headers);
    const carouselData: import('../types/WebsiteMonitoring').CarouselContent[] = [];
    
    for (const row of rows) {
      if (!row || row.length === 0) continue;
      
      try {
        const carouselId = this.getCellValue(row, this.findHeaderIndex(headerMap, ['輪播ID', 'carousel_id']));
        if (!carouselId) continue;
        
        const item: import('../types/WebsiteMonitoring').CarouselContent = {
          carousel_id: carouselId
        };
        
        const bannerTitle = this.getCellValue(row, this.findHeaderIndex(headerMap, ['標題', 'banner_title']));
        if (bannerTitle) item.banner_title = bannerTitle;
        
        const imageUrl = this.getCellValue(row, this.findHeaderIndex(headerMap, ['圖片網址', 'image_url']));
        if (imageUrl) item.image_url = imageUrl;
        
        const activityLink = this.getCellValue(row, this.findHeaderIndex(headerMap, ['活動連結', 'activity_link']));
        if (activityLink) item.activity_link = activityLink;
        
        const courseName = this.getCellValue(row, this.findHeaderIndex(headerMap, ['課程名稱', 'course_name']));
        if (courseName) item.course_name = courseName;
        
        const location = this.getCellValue(row, this.findHeaderIndex(headerMap, ['地點', 'location']));
        if (location) item.location = location;
        
        const instructor = this.getCellValue(row, this.findHeaderIndex(headerMap, ['講師', 'instructor']));
        if (instructor) item.instructor = instructor;
        
        const description = this.getCellValue(row, this.findHeaderIndex(headerMap, ['描述', 'description']));
        if (description) item.description = description;
        
        const extractionTimestamp = this.getCellValue(row, this.findHeaderIndex(headerMap, ['擷取時間', 'extraction_timestamp']));
        if (extractionTimestamp) item.extraction_timestamp = extractionTimestamp;
        
        carouselData.push(item);
      } catch (error) {
        console.warn('Failed to parse carousel row:', error);
      }
    }
    
    return carouselData;
  }

  /**
   * 解析課程取消資料
   * @private
   */
  private parseCancellationData(headers: string[], rows: any[][]): import('../types/WebsiteMonitoring').CourseCancellation[] {
    const headerMap = this.createHeaderMap(headers);
    const cancellationData: import('../types/WebsiteMonitoring').CourseCancellation[] = [];
    
    for (const row of rows) {
      if (!row || row.length === 0) continue;
      
      try {
        const cancellationId = this.getCellValue(row, this.findHeaderIndex(headerMap, ['取消ID', 'cancellation_id']));
        if (!cancellationId) continue;
        
        const item: import('../types/WebsiteMonitoring').CourseCancellation = {
          cancellation_id: cancellationId
        };
        
        const cancellationDate = this.getCellValue(row, this.findHeaderIndex(headerMap, ['取消日期', 'cancellation_date']));
        if (cancellationDate) item.cancellation_date = cancellationDate;
        
        const courseName = this.getCellValue(row, this.findHeaderIndex(headerMap, ['課程名稱', 'course_name']));
        if (courseName) item.course_name = courseName;
        
        const instructorName = this.getCellValue(row, this.findHeaderIndex(headerMap, ['講師姓名', 'instructor_name']));
        if (instructorName) item.instructor_name = instructorName;
        
        const extractionTimestamp = this.getCellValue(row, this.findHeaderIndex(headerMap, ['擷取時間', 'extraction_timestamp']));
        if (extractionTimestamp) item.extraction_timestamp = extractionTimestamp;
        
        cancellationData.push(item);
      } catch (error) {
        console.warn('Failed to parse cancellation row:', error);
      }
    }
    
    return cancellationData;
  }

  /**
   * 解析新聞資料
   * @private
   */
  private parseNewsData(headers: string[], rows: any[][]): import('../types/WebsiteMonitoring').NewsAnnouncement[] {
    const headerMap = this.createHeaderMap(headers);
    const newsData: import('../types/WebsiteMonitoring').NewsAnnouncement[] = [];
    
    for (const row of rows) {
      if (!row || row.length === 0) continue;
      
      try {
        const announcementId = this.getCellValue(row, this.findHeaderIndex(headerMap, ['公告ID', 'announcement_id']));
        if (!announcementId) continue;
        
        const item: import('../types/WebsiteMonitoring').NewsAnnouncement = {
          announcement_id: announcementId
        };
        
        const title = this.getCellValue(row, this.findHeaderIndex(headerMap, ['標題', 'title']));
        if (title) item.title = title;
        
        const publicationDate = this.getCellValue(row, this.findHeaderIndex(headerMap, ['發布日期', 'publication_date']));
        if (publicationDate) item.publication_date = publicationDate;
        
        const content = this.getCellValue(row, this.findHeaderIndex(headerMap, ['內容', 'content']));
        if (content) item.content = content;
        
        const extractionTimestamp = this.getCellValue(row, this.findHeaderIndex(headerMap, ['擷取時間', 'extraction_timestamp']));
        if (extractionTimestamp) item.extraction_timestamp = extractionTimestamp;
        
        newsData.push(item);
      } catch (error) {
        console.warn('Failed to parse news row:', error);
      }
    }
    
    return newsData;
  }

  /**
   * 解析媒體內容資料
   * @private
   */
  private parseMediaData(headers: string[], rows: any[][]): import('../types/WebsiteMonitoring').MediaContent[] {
    const headerMap = this.createHeaderMap(headers);
    const mediaData: import('../types/WebsiteMonitoring').MediaContent[] = [];
    
    for (const row of rows) {
      if (!row || row.length === 0) continue;
      
      try {
        const mediaId = this.getCellValue(row, this.findHeaderIndex(headerMap, ['媒體ID', 'media_id']));
        if (!mediaId) continue;
        
        const item: import('../types/WebsiteMonitoring').MediaContent = {
          media_id: mediaId
        };
        
        const courseTitle = this.getCellValue(row, this.findHeaderIndex(headerMap, ['課程標題', 'course_title']));
        if (courseTitle) item.course_title = courseTitle;
        
        const speakerName = this.getCellValue(row, this.findHeaderIndex(headerMap, ['講師姓名', 'speaker_name']));
        if (speakerName) item.speaker_name = speakerName;
        
        const startDate = this.getCellValue(row, this.findHeaderIndex(headerMap, ['開始日期', 'start_date']));
        if (startDate) item.start_date = startDate;
        
        const redirectUrl = this.getCellValue(row, this.findHeaderIndex(headerMap, ['重定向網址', 'redirect_url']));
        if (redirectUrl) item.redirect_url = redirectUrl;
        
        const mediaType = this.getCellValue(row, this.findHeaderIndex(headerMap, ['媒體類型', 'media_type']));
        if (mediaType) item.media_type = mediaType;
        
        const extractionTimestamp = this.getCellValue(row, this.findHeaderIndex(headerMap, ['擷取時間', 'extraction_timestamp']));
        if (extractionTimestamp) item.extraction_timestamp = extractionTimestamp;
        
        mediaData.push(item);
      } catch (error) {
        console.warn('Failed to parse media row:', error);
      }
    }
    
    return mediaData;
  }

  /**
   * 建立標題映射
   * @private
   */
  private createHeaderMap(headers: string[]): Map<string, number> {
    const headerMap = new Map<string, number>();
    headers.forEach((header, index) => {
      if (header) {
        headerMap.set(header.trim(), index);
      }
    });
    return headerMap;
  }
}

// 建立單例實例
export const excelReaderService = new ExcelReaderService();